# Generated by Django 5.1.4 on 2024-12-12 18:27

from django.db import migrations


def populate_initial_questions(apps, schema_editor):
    Question = apps.get_model('quizApp', 'Question')

    # List of questions and their options
    questions_data = [
        {
            'text': 'Who was the first president of the United States?',
            'option_1': 'George Washington',
            'option_2': 'Abraham Lincoln',
            'option_3': 'Thomas Jefferson',
            'option_4': 'John Adams',
            'correct_answer': 'George Washington'
        },
        {
            'text': 'In which year did the Titanic sink?',
            'option_1': '1912',
            'option_2': '1905',
            'option_3': '1920',
            'option_4': '1898',
            'correct_answer': '1912'
        },
        {
            'text': 'Who was the first man to set foot on the moon?',
            'option_1': 'Buzz Aldrin',
            'option_2': 'Yuri Gagarin',
            'option_3': 'Neil Armstrong',
            'option_4': 'Michael Collins',
            'correct_answer': 'Neil Armstrong'
        },
        {
            'text': 'What year did World War II end?',
            'option_1': '1943',
            'option_2': '1944',
            'option_3': '1945',
            'option_4': '1946',
            'correct_answer': '1945'
        },
        {
            'text': 'Who was the British Prime Minister during World War II?',
            'option_1': 'Neville Chamberlain',
            'option_2': 'Winston Churchill',
            'option_3': 'Clement Attlee',
            'option_4': 'Edward Heath',
            'correct_answer': 'Winston Churchill'
        },
        {
            'text': 'Which country was the first to grant women the right to vote?',
            'option_1': 'United States',
            'option_2': 'New Zealand',
            'option_3': 'Canada',
            'option_4': 'Australia',
            'correct_answer': 'New Zealand'
        },
        {
            'text': 'Who invented the telephone?',
            'option_1': 'Thomas Edison',
            'option_2': 'Nikola Tesla',
            'option_3': 'Alexander Graham Bell',
            'option_4': 'Guglielmo Marconi',
            'correct_answer': 'Alexander Graham Bell'
        },
        {
            'text': 'What was the name of the ship that carried the Pilgrims to America in 1620?',
            'option_1': 'Mayflower',
            'option_2': 'Santa Maria',
            'option_3': 'Titanic',
            'option_4': 'Endeavour',
            'correct_answer': 'Mayflower'
        },
        {
            'text': 'In which city was the Declaration of Independence signed?',
            'option_1': 'New York',
            'option_2': 'Philadelphia',
            'option_3': 'Boston',
            'option_4': 'Washington D.C.',
            'correct_answer': 'Philadelphia'
        },
        {
            'text': 'Which famous wall was torn down in 1989?',
            'option_1': 'The Berlin Wall',
            'option_2': 'The Great Wall of China',
            'option_3': 'Hadrian’s Wall',
            'option_4': 'The Wailing Wall',
            'correct_answer': 'The Berlin Wall'
        },
        {
            'text': 'Who was assassinated on April 4, 1968?',
            'option_1': 'Malcolm X',
            'option_2': 'John F. Kennedy',
            'option_3': 'Martin Luther King Jr.',
            'option_4': 'Robert F. Kennedy',
            'correct_answer': 'Martin Luther King Jr.'
        },
        {
            'text': 'Which ancient civilization built the pyramids?',
            'option_1': 'The Romans',
            'option_2': 'The Egyptians',
            'option_3': 'The Greeks',
            'option_4': 'The Mayans',
            'correct_answer': 'The Egyptians'
        },
        {
            'text': 'In which year did the Berlin Wall fall?',
            'option_1': '1985',
            'option_2': '1989',
            'option_3': '1991',
            'option_4': '1995',
            'correct_answer': '1989'
        },
        {
            'text': 'Who was the famous civil rights leader known for the "I Have a Dream" speech?',
            'option_1': 'Malcolm X',
            'option_2': 'Marcus Garvey',
            'option_3': 'Martin Luther King Jr.',
            'option_4': 'Rosa Parks',
            'correct_answer': 'Martin Luther King Jr.'
        },
        {
            'text': 'In what year did the United States declare independence from Britain?',
            'option_1': '1775',
            'option_2': '1776',
            'option_3': '1781',
            'option_4': '1790',
            'correct_answer': '1776'
        },
        {
            'text': 'What was the name of the first man-made satellite launched into space?',
            'option_1': 'Apollo 11',
            'option_2': 'Sputnik 1',
            'option_3': 'Explorer 1',
            'option_4': 'Vostok 1',
            'correct_answer': 'Sputnik 1'
        },
        {
            'text': 'Who was the first female Prime Minister of the United Kingdom?',
            'option_1': 'Margaret Thatcher',
            'option_2': 'Theresa May',
            'option_3': 'Indira Gandhi',
            'option_4': 'Golda Meir',
            'correct_answer': 'Margaret Thatcher'
        },
        {
            'text': 'Which war was fought between the northern and southern states of the U.S.?',
            'option_1': 'World War I',
            'option_2': 'World War II',
            'option_3': 'The Civil War',
            'option_4': 'The Revolutionary War',
            'correct_answer': 'The Civil War'
        },
        {
            'text': 'Who discovered America in 1492?',
            'option_1': 'Leif Erikson',
            'option_2': 'Christopher Columbus',
            'option_3': 'Ferdinand Magellan',
            'option_4': 'Amerigo Vespucci',
            'correct_answer': 'Christopher Columbus'
        },
        {
            'text': 'What ancient empire built the Colosseum?',
            'option_1': 'The Egyptians',
            'option_2': 'The Greeks',
            'option_3': 'The Romans',
            'option_4': 'The Persians',
            'correct_answer': 'The Romans'
        }
    ]

    # Creating Question objects
    for question in questions_data:
        Question.objects.create(**question)


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_questions),
    ]
